services:
  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
    tty: "true"
    working_dir: /app/front
    command: bash -c "npm install && npm run dev"