services:
  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
      - ./front/node_modules:/app/front/node_modules
    tty: "true"